branch-defaults:
  master:
    environment: google-music-dev
    group_suffix: null
global:
  application_name: google_music
  default_ec2_keyname: aws-kevin
  default_platform: Docker 1.12.6
  default_region: us-west-2
  profile: kevin
  sc: git
